### ISSUE TITLE
Doughnut initialSelectedDataIndexes cause error

### ISSUE THREAD

**Issue by BrightVan** [syncfusion/flutter-widgets#1279]
device: iphone simulator 14 pro
version: syncfusion_flutter_charts: ^22.1.34

if i set `initialSelectedDataIndexes: const [0],`, and then i select another index such as ` index 2`, it is ok. and then switch to another app, and come back, the initialSelectedDataIndexes and ` index 2` are both selected. the `initialSelectedDataIndexes` should not be reselected.

i fix this by do like this:
**initialSelectedDataIndexes: _isSelectionChanged ? [] : const [0],**
```
class _State extends State<MyView> {
  var _isSelectionChanged = false;

  @override
  Widget build(BuildContext context) {
    final data = context.watch<DataAnalysisModel>().gradeChartData;
    return Align(
      alignment: Alignment.topCenter,
      child: SizedBox(
        height: _chartHeight,
        child: SfCircularChart(
          onSelectionChanged: (selectionArgs) {
            setState(() {
              _isSelectionChanged = true;
            });
          },
          series: <CircularSeries>[
            // Render pie chart
            DoughnutSeries<PieChartData, String>(
              selectionBehavior: SelectionBehavior(
                enable: true,
                unselectedBorderWidth: 0,
                selectedBorderWidth: 1.5,
                selectedBorderColor:
                    context.colorScheme.onBackground.withOpacity(0.8),
                unselectedOpacity: 0.7,
                toggleSelection: false,
              ),
              legendIconType: LegendIconType.pentagon,
              initialSelectedDataIndexes: _isSelectionChanged ? [] : const [0],
             ...
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by sfHariHaraSudhan** [comment]
Hi @BrightVan,

We are able to replicate the reported issue regarding **“Initial-selected-index-is-not-working-while-rebuilding-the-circular-chart”** at our end and have logged a bug report for it in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out on July 18, 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the below feedback link.

Feedback link: https://www.syncfusion.com/feedback/44995/initial-selected-index-is-not-working-while-rebuilding-the-circular-chart.

Regards,
Hari Hara Sudhan. K

**Comment by sfHariHaraSudhan** [comment]
Hi @BrightVan,

Sorry for the inconvenience. We have fixed this issue but due to automation pending at our end, we are unable to move this fix to today’s weekly patch. We will move this issue fix in our SP release, which is expected to be rolled out at the end of July 2023. We will update you here once the release is rolled out and we appreciate your patience until then.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @BrightVan,

The reported issue regarding **Initial-selected-index-is-not-working-while-rebuilding-the-circular-chartseries** has been fixed and rolled out in our SP release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.2.5

Regards,
Hari Hara Sudhan. K.

**Comment by BrightVan** [comment]
> 
the bug is still exist on syncfusion_flutter_charts: ^22.2.8
