### ISSUE TITLE
[SfPdfViewer] not showing some bookmarks correctly.

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#128]
![Capture](https://user-images.githubusercontent.com/60609139/106146877-39a7f380-619d-11eb-8877-be8f3538d66d.PNG)

I made some sample bookmarks [1 to 6] and then used

`_pdfViewerKey.currentState?.openBookmarkView();`

to view the bookmarks. Here bookmarks which were written in English were shown correctly but the bookmarks which were written in other languages were not shown correctly. These bookmarks are correctly visible in other PDF viewers.

I also tried manually extracting the bookmark titles using

`_pdfBookmarkBase.bookmarks[i].title`

but then also the titles are exactly as shown in the image and not as expected.

**Comment by sarathkumar50** [comment]
Hi sagarkardani,

Greetings from Syncfusion.
We are confirmed the reported issue “Decoding other language text is not working for PDF bookmark parsing” Is a defect. We have fixed reported issue and checked with other language PDF.We will include this fix in our upcoming weekly patch release which is estimated to be available on 2nd Feb, 2020. 
The status of the bug can be track through below link: 
https://www.syncfusion.com/feedback/21729/unicode-text-is-not-proper-when-retrieving-from-bookmarks 

Regards,
Sarath Kumar Prakash.

**Comment by sagarkardani** [comment]
Now bookmarks which are having a page as destination are working correctly.

But the bookmarks which are linked to named destination or anchor still shows the titles as shown in the image and also this bookmarks are not jumping to that destination.

**Comment by sarathkumar50** [comment]
Hi sagarkardani,

We regret for the inconvenience.
We can reproduce the reported behavior and analyzing on the issue. We will update you with the analysis details by 10 February 2020. Kindly share us the issue causing document which will be helpful for us to provide a solution without any further delays.

Regards,
Sarath Kumar Prakash.

**Comment by sagarkardani** [comment]
Attached is the sample document.

[Sample Document.pdf](https://github.com/syncfusion/flutter-widgets/files/5949282/Sample.Document.pdf)




Below is the view of bookmarks in almost all PDF viewers
![Actual Bookmarks](https://user-images.githubusercontent.com/60609139/107323862-0c2c4580-6acd-11eb-890e-90d25d2dc325.PNG)




Below is the SfPdfViewer BookmarkView
![SfPDFViewer BookmarksView](https://user-images.githubusercontent.com/60609139/107324177-9d9bb780-6acd-11eb-8a2c-dbd0de506c8e.PNG)

**Comment by sarathkumar50** [comment]
Hi sagarkardani,

We have confirmed that the reported issue in bookmark is a defect. The issue fix will be included in our upcoming weekly release which will be scheduled to be available by February 16, 2021 tentatively.

Regards,
Sarath Kumar Prakash.

**Comment by weneverknow** [comment]
hello guys,
i have an issue. i have this doc https://www.mediafire.com/file/d10jv1rsn2a03t7/ca04725c-41b2-4a11-bd24-c0520c618ce9.pdf/file and the bookmark is show but if i click it does not work.
