### ISSUE TITLE
[syncfusion_flutter_calendar] Cannot drag horizontal scrollbar in timeline view (Desktop)

### ISSUE THREAD

**Issue by eliast96** [syncfusion/flutter-widgets#1912]
### Bug description

Cannot drag horizontal scrollbar in timeline view (on Desktop)
![image](https://github.com/syncfusion/flutter-widgets/assets/75338851/05a4f085-d20e-49c6-b3a9-8fd8a9955b3b)

### Steps to reproduce

create a timeline view and try dragging horizontal scrollbar with mouse

### Code sample

SfCalendarTheme(
                              data: SfCalendarThemeData(
                                timeTextStyle: const TextStyle(
                                  fontSize: 12,
                                  color: Colors.black,
                                ),
                              ),
                              child: SfCalendar(
                                headerHeight: 0,
                                view: CalendarView.timelineDay,
                                controller: _calendarController,
                                dataSource:
                                    AppointmentDataSource(_calendarAppointments)
                                      ..resources = _resourceCols,
                                todayHighlightColor: Colors.black,
                                selectionDecoration: BoxDecoration(
                                  color:
                                      Colors.lightBlueAccent.withOpacity(0.3),
                                ),
                                timeSlotViewSettings:
                                    const TimeSlotViewSettings(
                                  timeFormat: 'HH:mm',
                                  timeInterval: Duration(minutes: 30),
                                  timeIntervalHeight: 60,
                                ),
                                appointmentBuilder: (BuildContext context,
                                    CalendarAppointmentDetails details) {
                                  final Appointment event =
                                      details.appointments.first;

                                  return Container(
                                    width: details.bounds.width,
                                    height: details.bounds.height,
                                    decoration: BoxDecoration(
                                      color: event.color,
                                      borderRadius: BorderRadius.circular(5),
                                      border: event.color == placeholder_color
                                          ? Border.all(
                                              color: Colors.blue,
                                              width: 2.0,
                                            )
                                          : event.color ==
                                                  conflict_placeholder_color
                                              ? Border.all(
                                                  color: Colors.red,
                                                  width: 2.0,
                                                )
                                              : null,
                                    ),
                                    child: Center(
                                      child: Text(
                                        event.subject,
                                        style: const TextStyle(
                                          color: Colors.white,
                                          fontSize: 12,
                                        ),
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                  );
                                },
                              ),
                            )

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/syncfusion/flutter-widgets/assets/75338851/05a4f085-d20e-49c6-b3a9-8fd8a9955b3b)

</details>

### Stack Traces

No exception

### On which target platforms have you observed this bug?

Web, Web (Android browser), Web (iOS browser), Windows, macOS

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.5 23F79 darwin-arm64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Elias’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

• No issues found!

**Comment by eliast96** [comment]
I also noticed it can be seen in the official example:
https://flutter.syncfusion.com/#/event-calendar/getting-started
(switch to Timeline Week)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @eliast96 ,



The reported issue regarding the calendar timeline view horizontal scroll bar not being draggable has been fixed and rolled out in our weekly patch release. To avoid this issue please upgrade the syncfusion_flutter_calendar to the latest version below.



Latest version: https://pub.dev/packages/syncfusion_flutter_calendar/versions/26.1.40+1



Root cause: The scroll physics for the timeline view is set to NeverScrollPhysics due to different scrolling behaviors in mobile platforms and it prevents the timeline view switching.



If you have any further queries please get back to us, we are always happy to assist you.



Regards.

Yuvaraj.

**Comment by danielnababan** [comment]
Hi,

Is this issue solved already? i try to use the new package syncfusion_flutter_calendar: ^26.2.10
and the horizontal scrollbar still not able to drag to move.
please kindly confirm.
attached my sample project.

regards,
Daniel
[test_syncfusion_calendar.zip](https://github.com/user-attachments/files/16726567/test_syncfusion_calendar.zip)

**Comment by ThilipChandru** [comment]
Hi @danielnababan,

The reported issue has been fixed and rolled out in our Volume 3 main release. To avoid this issue, we kindly request that you upgrade the syncfusion_flutter_calendar package to the latest version below.

Calendar : [syncfusion_flutter_calendar: ^27.1.48](https://syncfusion-my.sharepoint.com/personal/thilipchandru_s_syncfusion_com/Documents/syncfusion_flutter_calendar:%20%5e27.1.48)

Root cause : The scrollPhysics is set to NeverScrollPhysics to prevent conflicts between switching the TimelineWeek view and scrolling between days within the week on mobile platforms.


Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need further assistance on this.

**Comment by danielnababan** [comment]
I have test. and the scrollbar is working now. Thanks
