### ISSUE TITLE
syncfusion_flutter_charts incompatible with flutter 3.22+

### ISSUE THREAD

**Issue by stsmedia** [syncfusion/flutter-widgets#1965]
### Bug description

Apologies if this is raised already and I have not been able to find the ticket.

It looks like flutter 3.22+ has breaking changes in the ColorScheme class which the chart package depends on.

```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

### Steps to reproduce

Compile flutter 2.33.2 project project with syncfusion 26.1.40 dependency

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-26.1.40/lib/src/theme/theme_widget.dart:123:47: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.
 - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../../tools/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'surfaceContainerHighest'.
        surfaceVariant: themeData.colorScheme.surfaceContainerHighest,
```

</details>

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Stefan's iPhone (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

```

</details>

**Comment by imskm** [comment]
I am facing the exam same issue.

I am using flutter version 3.19.1

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on KDE neon 5.27 5.15.0-79-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.1)
[✓] Connected device (3 available)
[✓] Network resources

```

**Comment by LokeshPalani** [comment]
Hi @stsmedia | @imskm,

We have updated our packages to be compatible with the **Flutter SDK v3.22.0**. In this version, Flutter introduced some breaking changes that were addressed in our packages. This may cause issues on your end if you are using a lower version of the Flutter SDK. So, we kindly request you to upgrade your **Flutter SDK version to 3.22.2** or else use the syncfusion_flutter_charts package version below [25.2.4](https://pub.dev/packages/syncfusion_flutter_gauges/versions/25.2.4) without caret (^) sign to prevent upgrading the Flutter SDK to the latest version. Additionally, we have shared user guide documentation link for compatible Syncfusion Flutter package version based on your Flutter SDK version and breaking changes link for your reference below. 

UG Link: https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

ColorScheme Breaking changes link : https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles#migration-guide

We hope it will help you to resolve the issue. If you are still facing issue, we recommend that you check by clearing the cache using the below mentioned methods:

- ​In the Flutter terminal, add the "flutter pub cache clean" command to clear all the cache.
- ​Close the running application and then add the "flutter clean" command.
- ​Delete the “pubspec.lock” file.
- ​Afterwards, add the "flutter pub get" command to get all the dependencies in the pubspec.yaml file.

Regards,
Lokesh P.

**Comment by stsmedia** [comment]
Hi Lokesh,

Thanks for this update. Hopefully this unblocks us.

I have just tried with the 26.1.41 release but the issue persists. I assume the fix will be in the next release or am I missing something?

```
../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-26.1.41/lib/src/theme/theme_widget.dart:123:47: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.
 - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../../tools/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'surfaceContainerHighest'.
        surfaceVariant: themeData.colorScheme.surfaceContainerHighest,
```

**Comment by LokeshPalani** [comment]
Hi @stsmedia | @imskm,

As mentioned in the previous update, the breaking changes were included in the **Flutter SDK version 3.22.0**. To avoid this issue, we kindly request you to make sure that you are using the latest **Flutter SDK version 3.22.2** for chart version [26.1.41+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.1.41+1). Please let us know if you need any further assistance.

ColorScheme Breaking changes link: https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles

Regards,
Lokesh P.

**Comment by stsmedia** [comment]
Hi Lokesh,

I have been using flutter 3.22.2 since I opened this ticket if you look at the ticket above.

```
flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (5 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

I was not aware you just released syncfusion_flutter_charts  26.1.41+1, but it appears it has a transitive dependency on syncfusion_flutter_core 26.1.41 which is causing the error I am still seeing:

```
../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-26.1.41/lib/src/theme/theme_widget.dart:123:47: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.
 - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../../tools/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'surfaceContainerHighest'.
        surfaceVariant: themeData.colorScheme.surfaceContainerHighest,
```

So to be clear, even after upgrading to syncfusion_flutter_charts: ^26.1.41+1 I am still seeing the error above.

Can you advise how exactly you are resolving this issue?

**Comment by stsmedia** [comment]
Thanks Lokesh, 

I was not aware you just released v 26.1.41+1. Can confirm it compiles with Flutter 3.22.2 now.

Appreciate your help with this!

**Comment by imskm** [comment]
Yeah upgrading to latest flutter and syncfusion_flutter_charts helped. I used different package for my need but now that syncfusion works I will change my code to use syncfusion.

Thanks
