### ISSUE TITLE
Column sorted (instead of filtered) when tapping filter icon

### ISSUE THREAD

**Issue by mathlizee** [syncfusion/flutter-widgets#2223]
### Bug description

Hello!

When tapping the filter icon, the column is sometimes (not always) sorted instead of opening the filter popup. I have provided a video capture that demonstrates the issue.

As you can see, when the filter icon is tapped, the column's sorting is sometimes changed instead of opening the filter popup. Furthermore, when I tap a 2nd time without moving my cursor, the filter popup opens normally as intended.

Sadly, I wasn't able to reproduce the issue in any of your examples. I have provided the code that customizes the filter and sort icons in my grid. Let me know if you need anything else!

Thanks!
Mathieu

### Steps to reproduce

1. Tap the filter icon
2. Sometimes, the column is sorted rather than the filter's popup menu opened

### Code sample

<details open><summary>Code sample</summary>

```dart
SfDataGridThemeData(
  headerColor: Theme.of(context).colorScheme.surfaceContainerHighest,
  selectionColor: Theme.of(context).colorScheme.primaryContainer,
  gridLineStrokeWidth: 0,
  sortIcon: Builder(
    builder: (context) {
      // Modifie l'icône de tri en fonction du tri appliqué sur la
      // colonne. L'icône tient aussi compte de la densité visuelle.
      //
      // Basé sur https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/sortIcon.html
      String columnName = '';
      context.visitAncestorElements((element) {
        if (element is GridHeaderCellElement) {
          columnName = element.column.columnName;
        }
        return true;
      });
  
      final column = _gridSource.sortedColumns
          .where((element) => element.name == columnName)
          .firstOrNull;
      final isSortedColumn = column != null;
  
      late IconData iconData;
      switch (column?.sortDirection) {
        case DataGridSortDirection.ascending:
          iconData = Icons.arrow_upward;
          break;
        case DataGridSortDirection.descending:
          iconData = Icons.arrow_downward;
          break;
        default:
          iconData = Icons.swap_vert;
      }
  
      return Icon(
        iconData,
        size: 25.0 + widget.verticalVisualDensity * 1.5,
        color: isSortedColumn
            ? dirtyColor
            : Theme.of(context).colorScheme.outline,
      );
    },
  ),
  filterIcon: Builder(
    builder: (context) {
      // Affiche un badge sur l'icône de filtre de la colonne si celle-ci
      // est filtrée. L'icône tient aussi compte de la densité visuelle.
      //
      // Basé sur https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/filterIcon.html
      String columnName = '';
      context.visitAncestorElements((element) {
        if (element is GridHeaderCellElement) {
          columnName = element.column.columnName;
        }
        return true;
      });
  
      final isFilteredColumn =
          _gridSource.filterConditions.containsKey(columnName);
  
      return Icon(
        Icons.filter_alt_outlined,
        size: 25.0 + widget.verticalVisualDensity * 1.5,
        color: isFilteredColumn
            ? dirtyColor
            : Theme.of(context).colorScheme.outline,
      );
    },
  ),
  )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![FilterBug](https://github.com/user-attachments/assets/bdfa902e-919c-4b62-b166-8ee14b9a35bf)

</details>

### Stack Traces

No stack trace.

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Using `syncfusion_flutter_datagrid: ^28.1.33`

```console
[✓] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.5247], locale en-CA)
[✓] Windows Version (Installed version of Windows is version 10 or higher)        
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)  
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.12.3)
[!] Android Studio (version 2022.1)
    ✗ Unable to determine bundled Java version.
[✓] Android Studio (version 2023.3)
[✓] VS Code, 64-bit edition (version 1.96.0)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,
 
In the SfDataGrid, the filter icon occupies the same space as the sort icon in the column header. When you tap on any area of the header, except where the filter icon is located, the grid triggers a sort action. However, if you specifically tap on the filter icon, the filter popup should open. Due to the overlap between the sorting and filtering areas, the sort action is triggered instead of the filter popup.
 
To resolve this issue, **you can wrap the filter icon inside a container and set explicit width and height for the icons**. This ensures that the space for the filter icon is clearly defined, allowing taps on the filter icon to reliably open the filter popup instead of triggering the sort action.

We have provided a code snippets and video reference for your reference. Please refer to the attached code for more details.

```
 filterIcon: Builder(
            builder: (context) {
              String columnName = '';
              context.visitAncestorElements((element) {
                if (element is GridHeaderCellElement) {
                  columnName = element.column.columnName;
                }
                return true;
              });

              final isFilteredColumn =
                  employeeDataSource.filterConditions.containsKey(columnName);

              return Container(
                width: 40,
                height: 40,
                color: Colors.green,
                child: Icon(
                  Icons.filter_alt_outlined,
                  size: 25.0 + verticalVisualDensity * 1.5,
                  color: isFilteredColumn ? Colors.red : Colors.black,
                ),
              );
            },
          ),
```

Regards,
Abinesh P

**Comment by mathlizee** [comment]
Hi @abineshPalanisamy,

Thanks for the fix! Everything is now working as expected.

Kind regards,
Mathieu

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,
 
In SfDataGrid, when you tap on any part of the header except where the filter icon is located, the grid triggers a sort action. This is because the sorting gesture is assigned to the entire header cell, except for the space reserved for the filter icon. This is the expected behavior on our end.
 
In your video, after careful analysis, we noticed that when the resizing indicator appears, you try to tap to open the popup menu. When this resizing indicator is visible, the focus is only on the entire header cell, not on the filter icon's space. **The small area between the filter icon and the gridline is also considered part of the header. So, performing an action in this intermediate space also triggers a sort action**. To open the popup without interruption, you **need to tap precisely on the area designated for the filter icon gesture**.

We have provided video for your reference. Please refer it for more details.

https://github.com/user-attachments/assets/b2c8c0ec-67af-4b07-a6cd-ef6b07984b16

 
Regards,
Abinesh P

**Comment by mathlizee** [comment]
Hi @abineshPalanisamy!

> In your video, after careful analysis, we noticed that when the resizing indicator appears, you try to tap to open the popup menu.

That is not entirely true... These are the steps I used to reproduce the issue:

1. I hover the filter icon
2. Then, I slide the mouse's cursor to the right until the resizing indicator appears
3. Next, I slide the mouse's cursor to the left until it is placed directly over the filter icon (the resizing indicator has disappeared by then)
5. Lastly, I click on the mouse button

When reproducing these steps, the column is sometimes sorted instead of opening the popup menu... Here's another capture that shows the issue:

![FilterIssue2](https://github.com/user-attachments/assets/18d75157-05d9-48d5-be45-4d776475a598)

Thanks again!
Mathieu

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,
 
We have reviewed your cases following the provided steps to reproduce the issue, but we were unable to replicate the problem on our end. To assist further, we have included a video reference and sample of our testing.
 
Please update the Flutter SDK and SfDataGrid to the latest versions and check if the issue persists. If you continue to encounter problems, kindly modify the attached sample to replicate the issue and provide clear and detailed steps to reproduce it. Sharing this additional information will help us address your request comprehensively and provide an appropriate solution.


**Video :** 

https://github.com/user-attachments/assets/dbfee3ff-0fa1-4afd-b4e5-a30225e17fc0



**Testing Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/18342518/SfDataGrid.zip)

Regards,
Abinesh P

**Comment by mathlizee** [comment]
Hi @abineshPalanisamy!

I was able to reproduce the issue after modifying the provided example:

![FilterIssue3](https://github.com/user-attachments/assets/09d2184b-e4ce-48fe-9b9b-7ce1e89a8e30)

[main.zip](https://github.com/user-attachments/files/18353888/main.zip)

I also discovered that the issue does not happen when the `onCellDoubleTap` callback is null. When it has a value, the filter popup appears after a longer delay because of the way the `GestureDetector` is implemented (see https://github.com/flutter/flutter/issues/106170). Maybe this delay causes an issue inside the grid?

Thanks again!
Mathieu

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,

Based on the provided details, we conducted a thorough analysis and examined the source closely. We used two GestureDetector widgets: one as the parent of the hole and another as the child, which serves as the parent of the Filter icon.

In the DataGrid, we employed the rendering concept to display the grid in the view. We were able to reproduce the issue by enabling multiple features, such as column resizing, column drag-and-drop, filtering, and onCellDoubleTap. After enabling these features, the issue occurred intermittently. 

Upon detailed investigation, we determined that the issue originates from the framework itself. When tapping on the child GestureDetector, the tap gesture is also recognized by the parent widget. However, when we attempted to reproduce the issue with a simplified sample, we were unable to replicate it at this time. 

Once we reproduce the issue on our end with the framework controls, we will report it to the framework team and share the logged issue details.

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @mathlizee,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K

**Comment by mathlizee** [comment]
Hi @ashok-kuvaraja,

Unfortunately, the issue is not resolved. I can still reproduce it with this test sample using the latest version of the grid.

[main.zip](https://github.com/user-attachments/files/20124331/main.zip)

Kind regards,
Mathieu

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,
 

We have checked your query at our end, and we are able to replicate that issue at our end. We have considered this as a  bug and logged a bug report regarding this in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release, which is expected to be rolled out on June 10, 2025. We will let you know once released, and we appreciate your patience until then. 

Disclaimer: Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization. 
 
Regards,
Abinesh P

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,

After a thorough investigation on our end, we were unable to identify the exact cause of the issue. It appears to be triggered by a combination of multiple features. This has caused a delay in resolving the reported issue.

We are currently working on a fix and are treating this with high priority. We will provide you with an update on or before June 12, 2025, after validating all the necessary details. We appreciate your patience and understanding in the meantime.

Regards,
Abinesh P

**Comment by abineshPalanisamy** [comment]
Hi @mathlizee ,

After a clear and thorough analysis, we have identified the exact root cause of the issue. We are working on fixing it on our end. The main release is scheduled for the coming week, so the bug fix will be included in the weekly release following the main release. We will inform you once it is released, and we appreciate your patience until then.
Regards,
Abinesh P

**Comment by Gowtham-SF4769** [comment]
Hi @mathlizee ,

We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version ([30.1.38](https://pub.dev/packages/syncfusion_flutter_datagrid)).

**Root cause:** The root cause of the issue is an unintended call to setState during dragging and when switching to the resize cursor. This unnecessary rebuild causes the parent widget to intercept the child’s gesture, which results in sorting being triggered instead of filtering when switching from the resize cursor.

If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.

Regards,
Gowtham R
