### ISSUE TITLE
[DataGrid] ctrl + A when filtered resets selected rows

### ISSUE THREAD

**Issue by dolbin-prime** [syncfusion/flutter-widgets#2266]
### Bug description

Hello, I'm using your DataGrid package, which is fantastic feature, but there is a small issue I found.

While I'm filtering a column, when I press `ctrl` + `A`, I expect that all visible rows(filtered rows) are selected plus, rows that were selected before filtering, remain as selected. But only currently visible rows are left in `selectedRows`.

I think it's because [the line in selection manager](https://github.com/syncfusion/flutter-widgets/blob/aa1c111cc020561f2b4259da8cfceb62cff0ee4c/packages/syncfusion_flutter_datagrid/lib/src/datagrid_widget/selection/selection_manager.dart#L1366):
```dart
void _processSelectedAll() {
...
  dataGridConfiguration.controller.selectedRows.clear(); // <-- here!
...
}
```
I think it should not clear selected rows unconditionally. 😃

### Steps to reproduce

1. Select some rows.
2. Check `selectedRows`.
3. Filter a column.
4. Press `ctrl` + `A`.
5. Check `selectedRows`.

### Code sample

.

### Screenshots or Video

.

### Stack Traces

.

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

.

**Comment by abineshPalanisamy** [comment]
Hi @dolbin-prime ,
 
In SfDataGrid, selection is based on the visible items in the grid. This is the expected behavior on our end. After filtering is applied, only the selected rows that remain visible are maintained in the [selectedRows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridController%2FselectedRows.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Ca4bc5d95fcdd4de9b9fc08dd444bc336%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638741814366743942%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=j5Oxf8mWDHAfLlik0gFrjIRn4pS537r8c9Q%2Bz9RZl14%3D&reserved=0) count.
 
If there are any misunderstandings regarding your requirements or if your needs differ, please provide specific and detailed information about the expected behavior. Sharing a video reference of the issue along with the reproduction steps would be very helpful. This additional information will enable us to address your request comprehensively and provide an appropriate solution.
 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment]
Hi @abineshPalanisamy, thank you for your response.

If that is the intent, then rows that are not currently included in the visible rows but were selected before filtering, should be deselected.

But it doesn't behave that way. This is even more pronounced when I enable the checkbox column, because the rows that were checked- which means selected - before filtering, remain checked when I come back after filtering and pressing `ctrl` + `A`.

If this is the intended behavior as you say, shouldn't the checked state be unchecked?

**Comment by abineshPalanisamy** [comment]
Hi @dolbin-prime 

Sorry for the inconvenience and delayed response. After a thorough analysis, we have identified this as a bug and have logged a report in our feedback portal. We will fix the issue and include the changes in our upcoming weekly patch release, expected to roll out on March 11, 2025. We will notify you once it is released, and we appreciate your patience in the meantime.

Disclaimer: Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization. 
 
Regards,
Abinesh P

**Comment by abineshPalanisamy** [comment]
Hi @dolbin-prime , 
 
We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([28.2.11](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fpackages%2Fsyncfusion_flutter_datagrid&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C7654522624e9453184fa08dd6138937d%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638773617796591227%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=PeinFtdTcIi%2B1AWTcT4azZIc5oD%2FcGUkmQT%2BSz7CTz4%3D&reserved=0)). 
 
Root cause :  In SfDataGrid, we maintain two collections: DataGridSource.rows and the effective rows collection. When sorting or filtering is performed, only the effective rows collection is affected, and changes are applied accordingly. However, for selection, we use the entire rows collection to perform selection and provide selected data. We do not consider the effective rows collection for selection, which causes a mismatch in the selected count when retrieving it after filtering.
If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.
 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment]
Hi @abineshPalanisamy, thanks for your support!

I'm afraid that the problem still exists... that is, `addedRows` and `DataGridController.effectiveRows` work perfectly, but `DataGridController.selectedRows` still don't contain the rows that were selected BEFORE filtering. I think the cause of this is that the following code still remains:
```dart
dataGridConfiguration.controller.selectedRows.clear();
```

BUT! I found that `RowSelectionManager._selectedRows` contain _the rows that were selected before filtering correctly_, but it is `private` so I can't access to it. So What I need is one of these options:
- support interface that I can refer to `RowSelectionManager._selectedRows`
- `DataGridController.selectedRows` should be the same with `RowSelectionManager._selectedRows`

I'm really sorry that I'm bothering you, but I need this feature! Please review my proposal.

Thank you.

**Comment by abineshPalanisamy** [comment]
Hi @dolbin-prime , 
 
In SfDataGrid, starting from version **28.2.11**, selection is handled based on visible rows only. **The selected details are maintained only for the rows currently available in the DataGrid**.
 
In your case, rows that were selected before filtering are not retained in selected details if they are no longer visible after filtering. From now on, selection and selected details will be based only on visible rows, which is the expected behavior.
 
However, we have a workaround to maintain selection details even after filtering. You need to maintain a flag list to store the selected rows. Using the onSelectionChanged event, you can add or remove rows from this list as they are selected or deselected. By accessing this list, you can retrieve the total selected rows, even after filtering.
 
We have included a sample for reference.

- **Sample:** [SfDataGrid.zip](https://github.com/user-attachments/files/19245013/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment]
Hi @abineshPalanisamy ,

Ok I see what you mean, and thanks to your sample code, I was able to implement what I wanted. I appreciate all your support ❤

Thank you!
