### ISSUE TITLE
Trackball not working properly with multiple series whose domains don't overlap

### ISSUE THREAD

**Issue by petoknm** [syncfusion/flutter-widgets#305]
I made an [example](https://github.com/petoknm/sf/blob/master/lib/main.dart) to demonstrate the problem.

Related to #224, #225.

I need to show multiple segments of essentially the same series, but since `LineSeries` joins all points it has, I need to use multiple `LineSeries` whose domains are non overlapping and this creates issues with the trackball and tooltip.

Let's have discussion on how we want to support this use case (if at all).

**Comment by Dharanipalani** [comment]
Hi @petoknm,

Thanks for the interest in our Flutter charts. We have analyzed your given example and trackball does not show properly for nearest point mode with empty points is now resolved in the latest version of the charts. Kindly upgrade the charts to the latest version from the below link.

**Latest version:** [https://pub.dev/packages/syncfusion_flutter_charts/versions/19.2.46+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.2.46+1)

Thaks,
Dharanitharan. P

**Comment by petoknm** [comment]
Still not working:

 - [ ] `tooltipDisplayMode: TrackballDisplayMode.groupAllPoints`
 - [ ] trackball is still jumping erratically to points that are definitely not closest, when in `tooltipDisplayMode: TrackballDisplayMode.nearestPoint`

Btw, why is the development and publishing of the releases not visible on github? you are publishing source anyway, being able to see the changes would have saved me some time diffing the releases to see what has changed.

**Comment by Dharanipalani** [comment]
Hi @petoknm,

We have analyzed your given code and would like to say that in the group mode there is only one trackball tooltip which shows the information about all series in that point index. In the give code, there is empty points for the second series which are all having data for the first series. As a result, it shows information for further points of the second at the end of first series which is an expected behavior. We suggest using the float all points mode for this scenario. Also, like to point out that in the nearest point mode, the nearest point is calculated based on both the x and y values and in the given code which displays the nearest point respect to this and worked as expected behavior. Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by petoknm** [comment]
Let me demonstrate the problem on video, so that we are clear on what I mean.

For the `groupAllPoints` mode:
 - [ ] trackball (the vertical line) cannot move to the second series

https://user-images.githubusercontent.com/5087675/125265648-55472680-e305-11eb-87b6-acda618d868f.mp4

For `nearestPoint` mode:
 - [ ] please tell me, in what non-euclidean space these are the nearest points...

https://user-images.githubusercontent.com/5087675/125265786-760f7c00-e305-11eb-9171-07f9f380d83e.mp4

The whole `leastX` thing in the code, does not sound like a valid approach to me.

**Comment by Dharanipalani** [comment]
Hi @petoknm,

We are analyzing on the reported scenario and will update you the further details within two business days (20/07/2021).

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @petoknm,

We apologize for the inconvenience. We are unable to give you the update due to technical difficulties. We will investigate and give additional information on or before July 27, 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by petoknm** [comment]
Is there any way I can help? I know that fixing this properly will require some significant refactoring because the code seems pretty convoluted. But I would rather, we take the time to fix this properly rather than rushing it and creating more issues down the road.

**Comment by petoknm** [comment]
Seems like too much to ask, since it requires changes in both development and organizational level, but embracing the open source development model would bring advantages in these situations. We could plan out a solution together, break down the tasks and work on them in parallel. Now, I feel, like I'm being left out of the solution making process, which just makes me uncertain if the solution you guys come up with is something I will agree with as a user.

**Comment by Dharanipalani** [comment]
Hi @petoknm,

Thank you for your time and consideration, as well as for your suggestions. We have evaluated the circumstances and determined that this is a trackball enhancement that will be incorporated in the future volume 3 main release, which is scheduled for release at the end of September 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P
