### ISSUE TITLE
type 'int' is not a subtype of type 'double' in type cast (syncfusion_flutter_sliders)

### ISSUE THREAD

**Issue by trueAtom** [syncfusion/flutter-widgets#307]
Hi, thx for the packages. I use syncfusion_flutter_sliders and set stepSize, but I get the error - type 'int' is not a subtype of type 'double' in type cast. Could you help me? Thx.

![image](https://user-images.githubusercontent.com/6696342/124962622-8551a980-e027-11eb-83ad-3a55705d0074.png)

**Comment by LakshmiRadhaKrishnan** [comment]
Hi trueAtom,

Greetings from Syncfusion support.

We have fixed the reported issue and it will be included in our next weekly release on July 20th, 2021. Kindly let us know if you need any further assistance with this.

Regards,
Lakshmi R.

**Comment by trueAtom** [comment]
> Hi trueAtom,
> 
> Greetings from Syncfusion support.
> 
> We have fixed the reported issue and it will be included in our next weekly release on July 20th, 2021. Kindly let us know if you need any further assistance with this.
> 
> Regards,
> Lakshmi R.

Thank you, the issue can be closed

**Comment by rohan20** [comment]
Hi,

The same issue still persists on `RangeSlider`. Can you please verify that this issue was fixed for `RangeSlider` too?

`syncfusion_flutter_sliders: ^19.4.48`

**Comment by ShahzadUmarBaig** [comment]
Issue still persists in version `syncfusion_flutter_sliders: ^23.2.4`.

```
======== Exception caught by scheduler library =====================================================
The following _TypeError was thrown during a scheduler callback:
type 'int' is not a subtype of type 'double'

When the exception was thrown, this was the stack: 
#0      RenderBaseRangeSlider.increasedStartValue (package:syncfusion_flutter_sliders/src/range_slider_base.dart:280:35)
#1      _RenderRangeSlider.assembleSemanticsNode (package:syncfusion_flutter_sliders/src/range_slider.dart:2216:7)
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4895:13)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4884:16)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4884:16)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4819:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4819:18)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4819:18)
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4819:18)
#9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4884:16)
#10     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4585:16)
#11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3548:25)
#12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1265:16)
#13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:21)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#19     _invoke (dart:ui/hooks.dart:170:13)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#21     _drawFrame (dart:ui/hooks.dart:140:31)
====================================================================================================
```
