### ISSUE TITLE
[syncfusion_flutter_charts] Null safety migration bug in `CircularSeriesRendererExtension`

### ISSUE THREAD

**Issue by bambinoua** [syncfusion/flutter-widgets#834]
I use `SfCircularChart` in my project. When I switch from light mode to dark mode or vise versa I have the exception:
```
Unexpected Null value
```
![index](https://user-images.githubusercontent.com/45417992/181499534-f0c0380e-4138-495c-b975-c650a7eaa4f5.jpg)

As you may see you compare `point.startAngle!` with `oldStartAngle!` but `oldStartAngle` is `null`. So we have a crash in the file `/lib/src/circular_chart/renderer/renderer_extension.dart`

I noticed that this crash is occurrend when I use my own `legendItemBuilder`. And moreover the prototype of `legendItemBuilder` is 
```dart
legendItemBuilder: (legendText, series, point, seriesIndex) {
  print(series); // <--- returns `Instance of 'DoughnutSeriesRendererExtension'`
  return MyWidget();
}
```
I am confident the other value it should be printed.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @bambinoua, 

Greetings from Syncfusion. Please find the response to your query below, 

**Query #1: As you may see you compare point.startAngle! with oldStartAngle! but oldStartAngle is null. So we have a crash in the file /lib/src/circular_chart/renderer/renderer_extension.dart** 

We have checked the [DoughnutSeries](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_charts%2Flatest%2Fcharts%2FDoughnutSeries-class.html&data=05%7C01%7Cyuvaraj.gajaraj%40syncfusion.com%7C6b8c4dd64a134953add908da81d4f40e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637965048864509066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gmNQPPKj4hoEmTxLWEn0gRI2j1L6QLcsNlz4wSMlfu0%3D&reserved=0) with the [legendItemBuilder ](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_charts%2Flatest%2Fcharts%2FLegend%2FlegendItemBuilder.html&data=05%7C01%7Cyuvaraj.gajaraj%40syncfusion.com%7C6b8c4dd64a134953add908da81d4f40e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637965048864509066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FKUHUFsbC%2Fbp1avhjjrRp28QilsdxLio%2FNwpR5pysHo%3D&reserved=0)in the following case, 

 * Check with the dynamic update using the update data source method. 
 * Check with updating the data source while changing the theme with a button click. 
 * Check with the [legendItemBuilder ](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_charts%2Flatest%2Fcharts%2FLegend%2FlegendItemBuilder.html&data=05%7C01%7Cyuvaraj.gajaraj%40syncfusion.com%7C6b8c4dd64a134953add908da81d4f40e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637965048864509066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FKUHUFsbC%2Fbp1avhjjrRp28QilsdxLio%2FNwpR5pysHo%3D&reserved=0)toggle before and after updating the data source.
 * Also check with changing the theme after the legend toggle. 

In these cases, the issue is not reproduced at our end, and we are not unaware of what the properties have you enabled in legend, and you mentioned that the exception occurs when using your own [legendItemBuilder](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_charts%2Flatest%2Fcharts%2FLegend%2FlegendItemBuilder.html&data=05%7C01%7Cyuvaraj.gajaraj%40syncfusion.com%7C6b8c4dd64a134953add908da81d4f40e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637965048864509066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FKUHUFsbC%2Fbp1avhjjrRp28QilsdxLio%2FNwpR5pysHo%3D&reserved=0). We have shared the sample below, please try to reproduce the reported issue and get back to us and also please mention the platform you are facing the issue, it will help us to assist you in a better way. 

Sample: [github_834.zip](https://github.com/syncfusion/flutter-widgets/files/9381790/github_834.zip)

**Query #2: print(series); // <--- returns `Instance of 'DoughnutSeriesRendererExtension'`** 

Here series is a [DoughnutSeriesRenderer](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_charts%2Flatest%2Fcharts%2FDoughnutSeriesRenderer-class.html&data=05%7C01%7Cyuvaraj.gajaraj%40syncfusion.com%7C6b8c4dd64a134953add908da81d4f40e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637965048864509066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B8ddTQlNRbNHePU3CESQs%2B7fr4zPu%2Ff5vT0v4itVIQk%3D&reserved=0) and it has the properties and value of the current doughnut series in the chart. So, you can access the properties and value and customize the legend item by series specific. 

Regards, 
Yuvaraj.

**Comment by bambinoua** [comment]
> As you may see you compare point.startAngle! with oldStartAngle! but oldStartAngle is null. So 
> we have a crash in the file /lib/src/circular_chart/renderer/renderer_extension.dart

I understand that you could not reproduce the crash and I could not to reproduce the crash on you **simple** example but the crash is present in real project!

The attached video explains the problem.

https://user-images.githubusercontent.com/45417992/187667610-4eae81e4-6f23-4ad7-85a2-0a41a6cdff76.mp4

**Comment by bambinoua** [comment]
> Here series is a `DoughnutSeriesRenderer` and it has the properties and value of the current > doughnut series in the chart. So, you can access the properties and value and customize the legend > item by series specific.

How come? If `DoughnutSeriesRenderer` is `CircularSeriesRenderer` which in its turn is `ChartSeriesRenderer` which **has no any** methods?

![1](https://user-images.githubusercontent.com/45417992/187668134-dc6a0734-f7f3-4570-a6d1-2ecd3339b86e.png)
![2](https://user-images.githubusercontent.com/45417992/187668137-76aac0b1-fd28-40e1-b60f-62e8f8ac6f86.png)

**Comment by bambinoua** [comment]
Any updates on this issue? I see you updates continuously but the bug is still there!

**Comment by bambinoua** [comment]
@Yuvaraj-Gajaraj 2,5 months to fix this bug?!! I even created a PR #916. Why is it so complex?

**Comment by bambinoua** [comment]
@Yuvaraj-Gajaraj or anybody could give me any answer?

**Comment by Yuvaraj-Gajaraj** [comment]
We apologize for the delay in addressing the reported issue. We were unable to reproduce it at our end, but we will be able to fix it based on the call stack you provided. The fix will be included in our weekly patch, which is expected to be released on March 7th 2023. We appreciate your patience until then.  

 In meantime, you can share more information to replicate the reported issue, it will be helpful to resolve the issue earlier.

**Comment by Yuvaraj-Gajaraj** [comment]
We have shared the feedback for the bug fix below for your reference. You can track the status of the bug fix here.

Feedback, https://www.syncfusion.com/feedback/41625/

**Comment by bambinoua** [comment]
@Yuvaraj-Gajaraj I got this
> Access Denied
> This private feedback is not associated with your account.

**Comment by bambinoua** [comment]
@Yuvaraj-Gajaraj you **promissed to include** my PR on March 7h! Today is already 15th. Why don't keep your word?

**Comment by Yuvaraj-Gajaraj** [comment]
Thanks for your patience. The reported issue that is getting a null check exception while changing the data source dynamically in SfCircularChart has been fixed and rolled out in our weekly patch release. To avoid this please upgrade the chart package to the latest version below.

Version, https://pub.dev/packages/syncfusion_flutter_charts/versions/20.4.54

**Comment by bambinoua** [comment]
@Yuvaraj-Gajaraj you **did not fix it**!!!

Please, please, please apply PR #916

**Comment by Yuvaraj-Gajaraj** [comment]
We will consider your code changes and plan to include them. Currently, we are working on this and we will let you know once the issue is fixed. We appreciate your patience until then.

**Comment by Yuvaraj-Gajaraj** [comment]
We have included the requested code change and rolled it out in our weekly patch releases. So, we request you update the chart package version to the latest one below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/21.1.37

**Comment by LokeshPalani** [comment]
We update the source of this repository only in the main release. Your issue fix has been moved to the weekly patch after the main release, so only this repository is not up to date with that fix. We hope the reported issue has been resolved in our latest chart packages. Please let us know if you need any further assistance on this.
